require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Demonav' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'DemonavTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable 
  use_flipper!({ 'Flipper' => '0.79.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Demonav-tvOS' do
  # Pods for Demonav-tvOS

  target 'Demonav-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
